version: "3.9"
services:
    web:
        image: lucasstirpe/tasklistwebapp.client
        build: 
            context: .
            dockerfile: TaskListWebApp/Client/Dockerfile
        ports:
            - "63500:80"
            - "63501:443"
        environment:
        - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - db
            - server
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Lucas000__%"
            ACCEPT_EULA: "Y"
        networks:
            appnet:
                ipv4_address: 172.24.2.1
    server:
        image: lucasstirpe/tasklistwebapp.server
        build:
            context: .
            dockerfile: TaskListWebApp/Server/Dockerfile
        ports: 
            - "65000:80"
            - "65001:43"
        environment:
        - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - db
        networks:
            appnet:
                ipv4_address: 172.24.2.2
networks:
    appnet:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.24.2.0/16"